### ISSUE TITLE
Build fails on OpenShift

### ISSUE THREAD

**Issue by siamaksade** [quarkusio/todo-demo-app#2]
When deploying on OpenShift 4 with:
```
oc new-app java~https://github.com/quarkusio/todo-demo-app
```

Build fails with this error:
```
[WARNING] The requested profile "openshift" could not be activated because it does not exist.
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:0.15.0:build (default) on project todo-backend: Failed to resolve application model io.quarkus.sample:todo-backend::jar:1.0-SNAPSHOT dependencies: Failed to inject extension deployment dependencies for io.quarkus.sample:todo-backend:jar:1.0-SNAPSHOT: org.eclipse.aether.transfer.TransferResource.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/io/File;Lorg/eclipse/aether/RequestTrace;)V -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.quarkus:quarkus-maven-plugin:0.15.0:build (default) on project todo-backend: Failed to resolve application model io.quarkus.sample:todo-backend::jar:1.0-SNAPSHOT dependencies
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

```

Full build log:
[todo-demo-app-1.log](https://github.com/quarkusio/todo-demo-app/files/3246577/todo-demo-app-1.log)

**Comment by siamaksade** [comment]
Same on OCP v3.11.43

**Comment by geoand** [comment]
Do you know what version of maven is being used in the builder image?

**Comment by siamaksade** [comment]
Apache Maven 3.5.0 (Red Hat 3.5.0-4.3)

**Comment by geoand** [comment]
Quarkus requires 3.5.3+ (see prerequisites in https://quarkus.io/guides/application-configuration-guide). IIRC s2i can be made to use mvnw, correct? If so, this project would need to include it
